# Final Project Milestone 3

## Wyatt Rasmussen
## DSC 540

**Topic:** Movies, this set of data will be pulled from Wikipedia

In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [2]:
fd = open("List of Golden Globe winners - Wikipedia.html", "r")
soup = BeautifulSoup(fd)
fd.close()

In [3]:
all_tables = soup.find_all("table")
print("Total number of tables are {} ".format(len(all_tables)))

Total number of tables are 5

In [4]:
data_table = soup.findAll("table", {"class": 'wikitable'})
print(type(data_table))

<class 'bs4.element.ResultSet'>

In [5]:
table = data_table[2]
# table
# commented out table because the output file looked awful

In [6]:
headers = table.tbody.findAll('tr', recursive=False)[0]
headers_list = [th for th in headers.findAll('th')]
print(len(headers_list))

8

In [7]:
headers_list

[<th>Year
 </th>,
 <th>Drama
 </th>,
 <th>Musical/Comedy
 </th>,
 <th>Drama Actor
 </th>,
 <th>Musical/Comedy Actor
 </th>,
 <th>Drama Actress
 </th>,
 <th>Musical/Comedy Actress
 </th>,
 <th>Director
 </th>]

In [8]:
headersList = headers_list[1:]
headersList

[<th>Drama
 </th>,
 <th>Musical/Comedy
 </th>,
 <th>Drama Actor
 </th>,
 <th>Musical/Comedy Actor
 </th>,
 <th>Drama Actress
 </th>,
 <th>Musical/Comedy Actress
 </th>,
 <th>Director
 </th>]

In [9]:
rows = table.findChildren(['tr'])

In [10]:
dataRows = []
for tr in rows:
    td = tr.find_all('td')
    row = [tr.text for tr in td]
    dataRows.append(row)

In [11]:
# dataRows
# commented out the dataRows because output file looked awful

In [12]:
goldenGlobeWinner = pd.DataFrame(dataRows, columns = ['Drama', 'Musical/Comedy', 'Drama Actor', 'Musical/Comedy Actor',
                                       'Drama Actress', 'Musical/Comedy Actress', 'Director'])
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Drama Actor,Musical/Comedy Actor,Drama Actress,Musical/Comedy Actress,Director
0,None,None,None,None,None,None,None
1,A Place in the Sun\n,An American in Paris\n,"Fredric March,Death of a Salesman\n","Danny Kaye,On the Riviera\n","Jane Wyman,The Blue Veil \n","June Allyson,Too Young to Kiss\n","Laslo Benedek,Death of a Salesman\n"
2,The Greatest Show on Earth\n,With a Song in My Heart\n,"Gary Cooper,High Noon\n","Donald O'Connor,Singin' in the Rain\n","Shirley Booth,Come Back, Little Sheba \n","Susan Hayward,With a Song in My Heart\n","Cecil B. DeMille,The Greatest Show on Earth\n"
3,The Robe\n,No award\n,"Spencer Tracy,The Actress\n","David Niven,The Moon Is Blue\n","Audrey Hepburn,Roman Holiday \n","Ethel Merman,Call Me Madam\n","Fred Zinnemann,From Here to Eternity\n"
4,On the Waterfront \n,Carmen Jones\n,"Marlon Brando,On the Waterfront\n","James Mason,A Star Is Born\n","Grace Kelly,The Country Girl \n","Judy Garland,A Star Is Born\n","Elia Kazan,On the Waterfront\n"

### Data Transformation 1 

**Dropping the first row of data since it is all empty**

In [13]:
goldenGlobeWinner = goldenGlobeWinner.drop(labels=0, axis=0)
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Drama Actor,Musical/Comedy Actor,Drama Actress,Musical/Comedy Actress,Director
1,A Place in the Sun\n,An American in Paris\n,"Fredric March,Death of a Salesman\n","Danny Kaye,On the Riviera\n","Jane Wyman,The Blue Veil \n","June Allyson,Too Young to Kiss\n","Laslo Benedek,Death of a Salesman\n"
2,The Greatest Show on Earth\n,With a Song in My Heart\n,"Gary Cooper,High Noon\n","Donald O'Connor,Singin' in the Rain\n","Shirley Booth,Come Back, Little Sheba \n","Susan Hayward,With a Song in My Heart\n","Cecil B. DeMille,The Greatest Show on Earth\n"
3,The Robe\n,No award\n,"Spencer Tracy,The Actress\n","David Niven,The Moon Is Blue\n","Audrey Hepburn,Roman Holiday \n","Ethel Merman,Call Me Madam\n","Fred Zinnemann,From Here to Eternity\n"
4,On the Waterfront \n,Carmen Jones\n,"Marlon Brando,On the Waterfront\n","James Mason,A Star Is Born\n","Grace Kelly,The Country Girl \n","Judy Garland,A Star Is Born\n","Elia Kazan,On the Waterfront\n"
5,East of Eden\n,Guys and Dolls\n,"Ernest Borgnine,Marty\n","Tom Ewell,The Seven Year Itch\n","Anna Magnani,The Rose Tattoo \n","Jean Simmons,Guys and Dolls\n","Joshua Logan,Picnic\n"

### Data Transformation 2

**Adding a year column for the year the award was won**

In [14]:
goldenGlobeWinner['Year'] = range(1952, len(goldenGlobeWinner) + 1952)
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Drama Actor,Musical/Comedy Actor,Drama Actress,Musical/Comedy Actress,Director,Year
1,A Place in the Sun\n,An American in Paris\n,"Fredric March,Death of a Salesman\n","Danny Kaye,On the Riviera\n","Jane Wyman,The Blue Veil \n","June Allyson,Too Young to Kiss\n","Laslo Benedek,Death of a Salesman\n",1952
2,The Greatest Show on Earth\n,With a Song in My Heart\n,"Gary Cooper,High Noon\n","Donald O'Connor,Singin' in the Rain\n","Shirley Booth,Come Back, Little Sheba \n","Susan Hayward,With a Song in My Heart\n","Cecil B. DeMille,The Greatest Show on Earth\n",1953
3,The Robe\n,No award\n,"Spencer Tracy,The Actress\n","David Niven,The Moon Is Blue\n","Audrey Hepburn,Roman Holiday \n","Ethel Merman,Call Me Madam\n","Fred Zinnemann,From Here to Eternity\n",1954
4,On the Waterfront \n,Carmen Jones\n,"Marlon Brando,On the Waterfront\n","James Mason,A Star Is Born\n","Grace Kelly,The Country Girl \n","Judy Garland,A Star Is Born\n","Elia Kazan,On the Waterfront\n",1955
5,East of Eden\n,Guys and Dolls\n,"Ernest Borgnine,Marty\n","Tom Ewell,The Seven Year Itch\n","Anna Magnani,The Rose Tattoo \n","Jean Simmons,Guys and Dolls\n","Joshua Logan,Picnic\n",1956

### Data Transformation 3

**This data transformation removes the \n from all data**

In [15]:
goldenGlobeWinner = goldenGlobeWinner.replace('\n',' ', regex=True) 
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Drama Actor,Musical/Comedy Actor,Drama Actress,Musical/Comedy Actress,Director,Year
1,A Place in the Sun,An American in Paris,"Fredric March,Death of a Salesman","Danny Kaye,On the Riviera","Jane Wyman,The Blue Veil","June Allyson,Too Young to Kiss","Laslo Benedek,Death of a Salesman",1952
2,The Greatest Show on Earth,With a Song in My Heart,"Gary Cooper,High Noon","Donald O'Connor,Singin' in the Rain","Shirley Booth,Come Back, Little Sheba","Susan Hayward,With a Song in My Heart","Cecil B. DeMille,The Greatest Show on Earth",1953
3,The Robe,No award,"Spencer Tracy,The Actress","David Niven,The Moon Is Blue","Audrey Hepburn,Roman Holiday","Ethel Merman,Call Me Madam","Fred Zinnemann,From Here to Eternity",1954
4,On the Waterfront,Carmen Jones,"Marlon Brando,On the Waterfront","James Mason,A Star Is Born","Grace Kelly,The Country Girl","Judy Garland,A Star Is Born","Elia Kazan,On the Waterfront",1955
5,East of Eden,Guys and Dolls,"Ernest Borgnine,Marty","Tom Ewell,The Seven Year Itch","Anna Magnani,The Rose Tattoo","Jean Simmons,Guys and Dolls","Joshua Logan,Picnic",1956

### Data Transformation 4

**Separating the movie from the actor, actresses, and director awards.**

In [16]:
new = goldenGlobeWinner["Drama Actor"].str.split(",", n = 1, expand = True)
new.head()

                 0                     1
1    Fredric March  Death of a Salesman
2      Gary Cooper            High Noon
3    Spencer Tracy          The Actress
4    Marlon Brando    On the Waterfront
5  Ernest Borgnine                Marty

In [17]:
goldenGlobeWinner['Drama Actor (Actor)']= new[0]
goldenGlobeWinner['Drama Actor (Movie)']= new[1]
goldenGlobeWinner.drop(labels=["Drama Actor"], axis=1, inplace=True)
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Musical/Comedy Actor,Drama Actress,Musical/Comedy Actress,Director,Year,Drama Actor (Actor),Drama Actor (Movie)
1,A Place in the Sun,An American in Paris,"Danny Kaye,On the Riviera","Jane Wyman,The Blue Veil","June Allyson,Too Young to Kiss","Laslo Benedek,Death of a Salesman",1952,Fredric March,Death of a Salesman
2,The Greatest Show on Earth,With a Song in My Heart,"Donald O'Connor,Singin' in the Rain","Shirley Booth,Come Back, Little Sheba","Susan Hayward,With a Song in My Heart","Cecil B. DeMille,The Greatest Show on Earth",1953,Gary Cooper,High Noon
3,The Robe,No award,"David Niven,The Moon Is Blue","Audrey Hepburn,Roman Holiday","Ethel Merman,Call Me Madam","Fred Zinnemann,From Here to Eternity",1954,Spencer Tracy,The Actress
4,On the Waterfront,Carmen Jones,"James Mason,A Star Is Born","Grace Kelly,The Country Girl","Judy Garland,A Star Is Born","Elia Kazan,On the Waterfront",1955,Marlon Brando,On the Waterfront
5,East of Eden,Guys and Dolls,"Tom Ewell,The Seven Year Itch","Anna Magnani,The Rose Tattoo","Jean Simmons,Guys and Dolls","Joshua Logan,Picnic",1956,Ernest Borgnine,Marty

**Repeating the process for the Musical/Comedy Actor Awards**

In [18]:
new1 = goldenGlobeWinner["Musical/Comedy Actor"].str.split(",", n = 1, expand = True)

In [19]:
goldenGlobeWinner['Musical/Comedy Actor (Actor)']= new1[0]
goldenGlobeWinner['Musical/Comedy Actor (Movie)']= new1[1]
goldenGlobeWinner.drop(labels=["Musical/Comedy Actor"], axis=1, inplace=True)
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Drama Actress,Musical/Comedy Actress,Director,Year,Drama Actor (Actor),Drama Actor (Movie),Musical/Comedy Actor (Actor),Musical/Comedy Actor (Movie)
1,A Place in the Sun,An American in Paris,"Jane Wyman,The Blue Veil","June Allyson,Too Young to Kiss","Laslo Benedek,Death of a Salesman",1952,Fredric March,Death of a Salesman,Danny Kaye,On the Riviera
2,The Greatest Show on Earth,With a Song in My Heart,"Shirley Booth,Come Back, Little Sheba","Susan Hayward,With a Song in My Heart","Cecil B. DeMille,The Greatest Show on Earth",1953,Gary Cooper,High Noon,Donald O'Connor,Singin' in the Rain
3,The Robe,No award,"Audrey Hepburn,Roman Holiday","Ethel Merman,Call Me Madam","Fred Zinnemann,From Here to Eternity",1954,Spencer Tracy,The Actress,David Niven,The Moon Is Blue
4,On the Waterfront,Carmen Jones,"Grace Kelly,The Country Girl","Judy Garland,A Star Is Born","Elia Kazan,On the Waterfront",1955,Marlon Brando,On the Waterfront,James Mason,A Star Is Born
5,East of Eden,Guys and Dolls,"Anna Magnani,The Rose Tattoo","Jean Simmons,Guys and Dolls","Joshua Logan,Picnic",1956,Ernest Borgnine,Marty,Tom Ewell,The Seven Year Itch

**Repeating again for Drama Actress**

In [20]:
new2 = goldenGlobeWinner["Drama Actress"].str.split(",", n = 1, expand = True)

In [21]:
goldenGlobeWinner['Drama Actress (Actress)']= new2[0]
goldenGlobeWinner['Drama Actress (Movie)']= new2[1]
goldenGlobeWinner.drop(labels=["Drama Actress"], axis=1, inplace=True)
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Musical/Comedy Actress,Director,Year,Drama Actor (Actor),Drama Actor (Movie),Musical/Comedy Actor (Actor),Musical/Comedy Actor (Movie),Drama Actress (Actress),Drama Actress (Movie)
1,A Place in the Sun,An American in Paris,"June Allyson,Too Young to Kiss","Laslo Benedek,Death of a Salesman",1952,Fredric March,Death of a Salesman,Danny Kaye,On the Riviera,Jane Wyman,The Blue Veil
2,The Greatest Show on Earth,With a Song in My Heart,"Susan Hayward,With a Song in My Heart","Cecil B. DeMille,The Greatest Show on Earth",1953,Gary Cooper,High Noon,Donald O'Connor,Singin' in the Rain,Shirley Booth,"Come Back, Little Sheba"
3,The Robe,No award,"Ethel Merman,Call Me Madam","Fred Zinnemann,From Here to Eternity",1954,Spencer Tracy,The Actress,David Niven,The Moon Is Blue,Audrey Hepburn,Roman Holiday
4,On the Waterfront,Carmen Jones,"Judy Garland,A Star Is Born","Elia Kazan,On the Waterfront",1955,Marlon Brando,On the Waterfront,James Mason,A Star Is Born,Grace Kelly,The Country Girl
5,East of Eden,Guys and Dolls,"Jean Simmons,Guys and Dolls","Joshua Logan,Picnic",1956,Ernest Borgnine,Marty,Tom Ewell,The Seven Year Itch,Anna Magnani,The Rose Tattoo

**Repeating again for Musical/Comedy Actress**

In [22]:
new3 = goldenGlobeWinner["Musical/Comedy Actress"].str.split(",", n = 1, expand = True)

In [23]:
goldenGlobeWinner['Musical/Comedy Actress (Actress)']= new3[0]
goldenGlobeWinner['Musical/Comedy Actress (Movie)']= new3[1]
goldenGlobeWinner.drop(labels=["Musical/Comedy Actress"], axis=1, inplace=True)
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Director,Year,Drama Actor (Actor),Drama Actor (Movie),Musical/Comedy Actor (Actor),Musical/Comedy Actor (Movie),Drama Actress (Actress),Drama Actress (Movie),Musical/Comedy Actress (Actress),Musical/Comedy Actress (Movie)
1,A Place in the Sun,An American in Paris,"Laslo Benedek,Death of a Salesman",1952,Fredric March,Death of a Salesman,Danny Kaye,On the Riviera,Jane Wyman,The Blue Veil,June Allyson,Too Young to Kiss
2,The Greatest Show on Earth,With a Song in My Heart,"Cecil B. DeMille,The Greatest Show on Earth",1953,Gary Cooper,High Noon,Donald O'Connor,Singin' in the Rain,Shirley Booth,"Come Back, Little Sheba",Susan Hayward,With a Song in My Heart
3,The Robe,No award,"Fred Zinnemann,From Here to Eternity",1954,Spencer Tracy,The Actress,David Niven,The Moon Is Blue,Audrey Hepburn,Roman Holiday,Ethel Merman,Call Me Madam
4,On the Waterfront,Carmen Jones,"Elia Kazan,On the Waterfront",1955,Marlon Brando,On the Waterfront,James Mason,A Star Is Born,Grace Kelly,The Country Girl,Judy Garland,A Star Is Born
5,East of Eden,Guys and Dolls,"Joshua Logan,Picnic",1956,Ernest Borgnine,Marty,Tom Ewell,The Seven Year Itch,Anna Magnani,The Rose Tattoo,Jean Simmons,Guys and Dolls

**Lastly repeating for Director**

In [24]:
new4 = goldenGlobeWinner["Director"].str.split(",", n = 1, expand = True)

In [25]:
goldenGlobeWinner['Director (Director)']= new4[0]
goldenGlobeWinner['Director (Movie)']= new4[1]
goldenGlobeWinner.drop(labels=["Director"], axis=1, inplace=True)
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Year,Drama Actor (Actor),Drama Actor (Movie),Musical/Comedy Actor (Actor),Musical/Comedy Actor (Movie),Drama Actress (Actress),Drama Actress (Movie),Musical/Comedy Actress (Actress),Musical/Comedy Actress (Movie),Director (Director),Director (Movie)
1,A Place in the Sun,An American in Paris,1952,Fredric March,Death of a Salesman,Danny Kaye,On the Riviera,Jane Wyman,The Blue Veil,June Allyson,Too Young to Kiss,Laslo Benedek,Death of a Salesman
2,The Greatest Show on Earth,With a Song in My Heart,1953,Gary Cooper,High Noon,Donald O'Connor,Singin' in the Rain,Shirley Booth,"Come Back, Little Sheba",Susan Hayward,With a Song in My Heart,Cecil B. DeMille,The Greatest Show on Earth
3,The Robe,No award,1954,Spencer Tracy,The Actress,David Niven,The Moon Is Blue,Audrey Hepburn,Roman Holiday,Ethel Merman,Call Me Madam,Fred Zinnemann,From Here to Eternity
4,On the Waterfront,Carmen Jones,1955,Marlon Brando,On the Waterfront,James Mason,A Star Is Born,Grace Kelly,The Country Girl,Judy Garland,A Star Is Born,Elia Kazan,On the Waterfront
5,East of Eden,Guys and Dolls,1956,Ernest Borgnine,Marty,Tom Ewell,The Seven Year Itch,Anna Magnani,The Rose Tattoo,Jean Simmons,Guys and Dolls,Joshua Logan,Picnic

### Data Transformation 5

**Setting the year as the index**

In [26]:
goldenGlobeWinner = goldenGlobeWinner.set_index('Year')
goldenGlobeWinner.head()

,Drama,Musical/Comedy,Drama Actor (Actor),Drama Actor (Movie),Musical/Comedy Actor (Actor),Musical/Comedy Actor (Movie),Drama Actress (Actress),Drama Actress (Movie),Musical/Comedy Actress (Actress),Musical/Comedy Actress (Movie),Director (Director),Director (Movie)
Year,,,,,,,,,,,,
1952,A Place in the Sun,An American in Paris,Fredric March,Death of a Salesman,Danny Kaye,On the Riviera,Jane Wyman,The Blue Veil,June Allyson,Too Young to Kiss,Laslo Benedek,Death of a Salesman
1953,The Greatest Show on Earth,With a Song in My Heart,Gary Cooper,High Noon,Donald O'Connor,Singin' in the Rain,Shirley Booth,"Come Back, Little Sheba",Susan Hayward,With a Song in My Heart,Cecil B. DeMille,The Greatest Show on Earth
1954,The Robe,No award,Spencer Tracy,The Actress,David Niven,The Moon Is Blue,Audrey Hepburn,Roman Holiday,Ethel Merman,Call Me Madam,Fred Zinnemann,From Here to Eternity
1955,On the Waterfront,Carmen Jones,Marlon Brando,On the Waterfront,James Mason,A Star Is Born,Grace Kelly,The Country Girl,Judy Garland,A Star Is Born,Elia Kazan,On the Waterfront
1956,East of Eden,Guys and Dolls,Ernest Borgnine,Marty,Tom Ewell,The Seven Year Itch,Anna Magnani,The Rose Tattoo,Jean Simmons,Guys and Dolls,Joshua Logan,Picnic

### Final Dataframe

In [27]:
goldenGlobeWinner

,Drama,Musical/Comedy,Drama Actor (Actor),Drama Actor (Movie),Musical/Comedy Actor (Actor),Musical/Comedy Actor (Movie),Drama Actress (Actress),Drama Actress (Movie),Musical/Comedy Actress (Actress),Musical/Comedy Actress (Movie),Director (Director),Director (Movie)
Year,,,,,,,,,,,,
1952,A Place in the Sun,An American in Paris,Fredric March,Death of a Salesman,Danny Kaye,On the Riviera,Jane Wyman,The Blue Veil,June Allyson,Too Young to Kiss,Laslo Benedek,Death of a Salesman
1953,The Greatest Show on Earth,With a Song in My Heart,Gary Cooper,High Noon,Donald O'Connor,Singin' in the Rain,Shirley Booth,"Come Back, Little Sheba",Susan Hayward,With a Song in My Heart,Cecil B. DeMille,The Greatest Show on Earth
1954,The Robe,No award,Spencer Tracy,The Actress,David Niven,The Moon Is Blue,Audrey Hepburn,Roman Holiday,Ethel Merman,Call Me Madam,Fred Zinnemann,From Here to Eternity
1955,On the Waterfront,Carmen Jones,Marlon Brando,On the Waterfront,James Mason,A Star Is Born,Grace Kelly,The Country Girl,Judy Garland,A Star Is Born,Elia Kazan,On the Waterfront
1956,East of Eden,Guys and Dolls,Ernest Borgnine,Marty,Tom Ewell,The Seven Year Itch,Anna Magnani,The Rose Tattoo,Jean Simmons,Guys and Dolls,Joshua Logan,Picnic
...,...,...,...,...,...,...,...,...,...,...,...,...
2017,Moonlight,La La Land,Casey Affleck,Manchester by the Sea,Ryan Gosling,La La Land,Isabelle Huppert,Elle,Emma Stone,La La Land,Damien Chazelle,La La Land
2018,"Three Billboards Outside Ebbing, Missouri",Lady Bird,Gary Oldman,Darkest Hour,James Franco,The Disaster Artist,Frances McDormand,"Three Billboards Outside Ebbing, Missouri",Saoirse Ronan,Lady Bird,Guillermo del Toro,The Shape of Water
2019,Bohemian Rhapsody,Green Book,Rami Malek,Bohemian Rhapsody,Christian Bale,Vice,Glenn Close,The Wife,Olivia Colman,The Favourite,Alfonso Cuarón,Roma
2020,1917,Once Upon a Time in Hollywood,Joaquin Phoenix,Joker,Taron Egerton,Rocketman,Renée Zellweger,Judy,Awkwafina,The Farewell,Sam Mendes,1917
2021,Nomadland,Borat Subsequent Moviefilm,Chadwick Boseman,Ma Rainey's Black Bottom,Sacha Baron Cohen,Borat Subsequent Moviefilm,Andra Day,The United States vs. Billie Holiday,Rosamund Pike,I Care a Lot,Chloé Zhao,Nomadland

In [28]:
goldenGlobeWinner.to_csv('goldenGlobeWinner.csv', index=False)